steps:
  - name: 'gcr.io/cloudbuild/python'
    args: ['-m', 'pip', 'install', '-r', 'requirements.txt']
  - name: 'gcr.io/cloudbuild/python'
    args: ['-m', 'flask', 'run', '--host=0.0.0.0', '--port=8080']
  - name: 'gcr.io/cloudbuild/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-run-demo-reverse-txt/us-central1/text-reversal-app', '.']
  - name: 'gcr.io/cloudbuild/docker'
    args: ['push', 'us-central1-docker.pkg.dev/cloud-run-demo-reverse-txt/us-central1/text-reversal-app']

images:
  - 'us-central1-docker.pkg.dev/cloud-run-demo-reverse-txt/us-central1/text-reversal-app'
